---
apiVersion: batch/v1
kind: Job
metadata:
  name: contour-certgen-v1.15.0
  namespace: projectcontour
spec:
  template:
    spec:
      containers:
      - name: contour
        image: projectcontour/contour:v1.15.0
        imagePullPolicy: IfNotPresent
